with-expecter: true
filename: "mock_{{.InterfaceName | snakecase}}.go"
dir: "{{.InterfaceDir}}/mocks"
mockname: "Mock{{.InterfaceName}}"
outpkg: "mocks"
packages:
  github.com/nikivavlt/url-shortener/user/internal/service:
    interfaces:
      UserRepository: {}
      Cache: {}
      Auth: {}
