with-expecter: true
filename: "mock_{{.InterfaceName | snakecase}}.go"
dir: "{{.InterfaceDir}}/mocks"
mockname: "Mock{{.InterfaceName}}"
outpkg: "mocks"
packages:
  github.com/yourname/url-shortener/user/internal/repository:
    interfaces:
      UserRepository:
      SessionRepository:
  github.com/yourname/url-shortener/user/internal/service:
    interfaces:
      TokenIssuer:
